[pytest]
norecursedirs = experiments
pythonpath = .
markers =
    integration: mark a test as an integration test.

filterwarnings =
    ignore::DeprecationWarning:chromadb.*:
    ignore::RuntimeWarning:litellm.*:
